# -*- mode: python ; coding: utf-8 -*-

"""PyInstaller spec for Academic Tracker desktop build."""

import sys
from pathlib import Path

BLOCK_CIPHER_LIST = None

a = Analysis(
    ["backend/desktop.py"],
    pathex=[str(Path("backend").resolve())],
    binaries=[],
    datas=[
        ("frontend/dist", "frontend/dist"),
        ("backend/alembic", "alembic"),
        ("backend/alembic.ini", "."),
        ("assets", "assets"),
    ],
    hiddenimports=[
        "app",
        "app.main",
        "app.config",
        "app.db",
        "app.models",
        "app.schemas",
        "app.api",
        "app.api.router",
        "app.api.carreras",
        "app.api.semestres",
        "app.api.materias",
        "app.api.evaluaciones",
        "app.api.clases",
        "app.api.correlativas",
        "app.api.importer",
        "app.api.cronograma",
        "app.api.analytics",
        "app.api.config_asistencia",
        "app.services",
        "app.services.base",
        "app.services.importer",
        "app.services.analytics",
        "uvicorn",
        "uvicorn.logging",
        "uvicorn.loops.auto",
        "uvicorn.loops.asyncio",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.http.h11_impl",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.protocols.websockets.wsproto_impl",
        "uvicorn.middleware.proxy_headers",
        "uvicorn.middleware.wsgi",
        "websockets",
        "websockets.legacy",
        "websockets.legacy.handshake",
        "websockets.legacy.server",
        "websockets.legacy.client",
        "h11",
        "wsproto",
        "sqlalchemy",
        "sqlalchemy.ext",
        "sqlalchemy.sql",
        "alembic",
        "alembic.runtime",
        "alembic.operations",
        "alembic.ddl",
        "alembic.autogenerate",
        "openpyxl",
        "openpyxl.cell",
        "openpyxl.reader",
        "openpyxl.writer",
        "openpyxl.styles",
        "openpyxl.worksheet",
        "openpyxl.workbook",
        "openpyxl.formatting",
        "openpyxl.chart",
        "openpyxl.chart.series",
        "openpyxl.descriptors",
        "openpyxl.xml",
        "openpyxl.packaging",
        "webview",
        "webview.platforms",
        "webview.platforms.edgechromium",
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "test",
        "unittest",
        "setuptools",
        "pip",
        "pyinstaller",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="AcademicTracker",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=["vcruntime*.dll"],
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="assets/icon.ico",
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=["vcruntime*.dll"],
    name="AcademicTracker",
)
