"""add hora to evaluacion

Revision ID: 7270512768b4
Revises: 91530e4419d7
Create Date: 2026-06-23 07:40:40.467865
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7270512768b4'
down_revision: Union[str, None] = '91530e4419d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluaciones', sa.Column('hora', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluaciones', 'hora')
    # ### end Alembic commands ###
