"""add codigo to materia

Revision ID: 7b752e7e9ce2
Revises: b9cad2fe0f98
Create Date: 2026-06-22 21:20:13.131188
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7b752e7e9ce2'
down_revision: Union[str, None] = 'b9cad2fe0f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materias', sa.Column('codigo', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materias', 'codigo')
    # ### end Alembic commands ###
