"""add_duracion_to_materia

Revision ID: ae8034525350
Revises: 7270512768b4
Create Date: 2026-06-23 18:35:44.138406
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ae8034525350'
down_revision: Union[str, None] = '7270512768b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materias', sa.Column('duracion', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materias', 'duracion')
    # ### end Alembic commands ###
