"""initial

Revision ID: b23c34b4f379
Revises: 
Create Date: 2026-06-22 20:10:07.341584
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b23c34b4f379'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('escala_nota_min', sa.Integer(), nullable=False),
    sa.Column('escala_nota_max', sa.Integer(), nullable=False),
    sa.Column('nota_aprobacion', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('semestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrera_id', 'numero', 'anio', name='uq_semestre_carrera_numero_anio')
    )
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.Column('profesor', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.CheckConstraint("estado IN ('cursando', 'aprobada', 'recursando', 'libre')", name='ck_materia_estado'),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('asistio', sa.Boolean(), nullable=False),
    sa.Column('tema', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clases_fecha'), 'clases', ['fecha'], unique=False)
    op.create_index(op.f('ix_clases_materia_id'), 'clases', ['materia_id'], unique=False)
    op.create_table('config_asistencia',
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('asistencia_minima_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('materia_id')
    )
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('nota_obtenida', sa.Float(), nullable=True),
    sa.Column('nota_simulada', sa.Float(), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.CheckConstraint("tipo IN ('parcial', 'recuperatorio', 'tp', 'final', 'coloquio')", name='ck_evaluacion_tipo'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_fecha'), 'evaluaciones', ['fecha'], unique=False)
    op.create_index(op.f('ix_evaluaciones_materia_id'), 'evaluaciones', ['materia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluaciones_materia_id'), table_name='evaluaciones')
    op.drop_index(op.f('ix_evaluaciones_fecha'), table_name='evaluaciones')
    op.drop_table('evaluaciones')
    op.drop_table('config_asistencia')
    op.drop_index(op.f('ix_clases_materia_id'), table_name='clases')
    op.drop_index(op.f('ix_clases_fecha'), table_name='clases')
    op.drop_table('clases')
    op.drop_table('materias')
    op.drop_table('semestres')
    op.drop_table('carreras')
    # ### end Alembic commands ###
