"""add correlatividades

Revision ID: b9cad2fe0f98
Revises: 1de84fc98532
Create Date: 2026-06-22 21:13:59.488111
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b9cad2fe0f98'
down_revision: Union[str, None] = '1de84fc98532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlatividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('correlativa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['correlativa_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlatividades_materia_id'), 'correlatividades', ['materia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correlatividades_materia_id'), table_name='correlatividades')
    op.drop_table('correlatividades')
    # ### end Alembic commands ###
